# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cryptoAlarmUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Crypto import Crypto

class Ui_MainWindow(object):
    # UI front end code generated from QtDesigner BEGIN *******************************
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 257)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushCrypto = QtWidgets.QPushButton(self.centralwidget)
        self.pushCrypto.setGeometry(QtCore.QRect(50, 90, 71, 61))
        self.pushCrypto.setObjectName("pushCrypto")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 90, 301, 61))
        self.label.setObjectName("label")
        self.textCrypto = QtWidgets.QTextEdit(self.centralwidget)
        self.textCrypto.setGeometry(QtCore.QRect(50, 40, 381, 41))
        self.textCrypto.setText("ellipsis")
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textCrypto.setFont(font)
        self.textCrypto.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textCrypto.setObjectName("textCrypto")
        self.textCrypto.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 21))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.menuEdit.addAction(self.actionAdd)
        self.menuEdit.addAction(self.actionRemove)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.textGreater = QtWidgets.QTextEdit(self.centralwidget)
        self.textGreater.setGeometry(QtCore.QRect(370, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textGreater.setFont(font)
        self.textGreater.setObjectName("textGreater")
        self.textGreater.setAlignment(QtCore.Qt.AlignCenter)
        self.textLesser = QtWidgets.QTextEdit(self.centralwidget)
        self.textLesser.setGeometry(QtCore.QRect(370, 120, 61, 31))
        self.textLesser.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textLesser.setFont(font)
        self.textLesser.setObjectName("textLesser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 90, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 120, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(140, 160, 191, 31))
        self.labelStatus.setText("")
        self.labelStatus.setObjectName("labelStatus")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # These 2 below functions are not auto generated by QtDesigner
        self.connectUi(MainWindow)
        self.initializeUi()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushCrypto.setText(_translate("MainWindow", "Alarm"))
        self.label.setText(_translate("MainWindow", ""))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionRemove.setText(_translate("MainWindow", "Remove"))
        self.label_2.setText(_translate("MainWindow", ">="))
        self.label_3.setText(_translate("MainWindow", "<="))

    def connectUi(self,MainWindow):
        self.pushCrypto.clicked.connect(self.clickedPushCrypto)
        #self.textCrypto.installEventFilter(MainWindow)  # Add listener for ticker texbox
        self.textCrypto.textChanged.connect(self.clickedPushCrypto)

    def initializeUi(self):
        self.cryptoObj = None

    # UI front end code generated from QtDesigner END *******************************



    def eventFilter(self, source, event):
        if event.type() == QtCore.QEvent.KeyPress and source is self.text_box:
            if event.key() == QtCore.Qt.Key_Return and self.text_box.hasFocus():
               self.clickedPushCrypto()

    def clickedPushCrypto(self):
        doCryptoInit = False
        self.labelStatus.setText("")
        try:
            # Get ticker name from the textbox
            tickerName = self.textCrypto.toPlainText().lower()

            if self.cryptoObj is not None:
                doCryptoInit = self.cryptoObj.tickerName != tickerName
            else:
                doCryptoInit = True

            if doCryptoInit:
                # Initialize crypto object if it wasn't
                self.cryptoObj = Crypto(tickerName=tickerName, database="Coingecko", tickerBase="usd")
                # Download thumbnail image to img folder
                self.cryptoObj.downloadThumbNail(fileName = "%s.png" % tickerName)


            self.cryptoObj.getData()
            self.label.setText("<b>%s :</b> %s <br><b>Price :</b> %.3f<br><b>Volume :</b> %d<br><b>Market Cap :</b> %d " % (self.cryptoObj.tickerName.upper(),self.cryptoObj.time,self.cryptoObj.price,self.cryptoObj.volume,self.cryptoObj.marketCap))
            self.pushCrypto.setStyleSheet("QPushButton{ image: url(../img/%s.png); }" % tickerName)
            self.pushCrypto.setText("")

        except Exception as err:
            self.labelStatus.setText("Error %s" % err)
            self.labelStatus.setStyleSheet("color : red")
            pass


        self.updateGui()

    def updateGui(self):
        self.label.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
